## [技术指标14：凯尔特纳通道 Technical Indicator 14: Keltner Channels (KC)]{style="color:blue"}

<span style="color:red;font-weight:700;font-size:18px">Internal Version, DO NOT disseminate!</span>  
  
<span style="color:red;font-weight:700;font-size:18px">内部版本 请勿外传!</span> 



`In Progress` 


<div style="text-align: right;">
**返回目录  **[快速索引 Quick Table of Contents] 
</div>




<!-- Disclaimer section with a gray bar -->
<div style="width: 100%; height: 20px; background-color: grey;"></div>

<!-- Disclaimer Text -->
<div style="padding: 20px; margin-top: 20px; background-color: #f1f1f1;">
    内部资料，请勿外传! 

    Internal documents, please do not disseminate! 

    本网页模型搭建说明及模型网络应用仅供参考。无论是所含信息还是所表达的观点，
    均不得明示或暗示为任何形式的建议、提供、招揽、邀请、广告、诱导、推荐或代表，
    以买卖任何证券、金融工具或任何投资或其他特定产品。

    The web-based Quantitative Model e-Manual and web application are for information
    purposes only. The information and opinion contained and expressed herein, shall not,
    and shall not be deemed to, construed, expressly or impliedly, as advice, offer or
    solicitation of an offer, invitation, advertisement, inducement, recommendation, or
    representation of any kind or form whatsoever to buy or sell any security, financial
    instrument or any investment or other specific product.
</div>






